import {
  getUserInfo,
  getAllSports,
  getPropsSport,
  getMyProps,
  getEachProp,
  withdrawProp,
  getFpsSport,
  getFantasyPoints,
  getUserAddress,
  addUserAddress,
  getStates,
  addIdentityVerify,
  submitProjections,
  getFaq,
  getUrls,
  getRefHistory,
  getAddPhone,
  postSendSms,
  postVerifySms,
  getTxHistory,
  getWithdrawHistory,
  postRedeemCode,
  getWithdrawCash,
  getWithdrawMethod,
  getDepositCash,
  postDeposit,
} from "./APIbase";

var APIURLs = {
  getUserInfo,
  getAllSports,
  getPropsSport,
  getMyProps,
  getEachProp,
  withdrawProp,
  getFpsSport,
  getFantasyPoints,
  getUserAddress,
  addUserAddress,
  getStates,
  addIdentityVerify,
  submitProjections,
  getFaq,
  getUrls,
  getRefHistory,
  getAddPhone,
  postSendSms,
  postVerifySms,
  getTxHistory,
  getWithdrawHistory,
  postRedeemCode,
  getWithdrawCash,
  getWithdrawMethod,
  getDepositCash,
  postDeposit,
};

export { APIURLs };
